### ISSUE TITLE
Internationalization on tests

### ISSUE THREAD

**Issue by genesis06** [NativeScript/nativescript-dev-appium#104]
Hi, 

Is it possible to use internationalization with nativescript-dev-appium? I tried it out but I got errors.. I'm using nativescript-i18n in my application.

Kind regards,
Génesis

**Comment by SvetoslavTsenov** [comment]
Hi @ genesis06,

Could you please elaborate more about the errors you get? Are you trying to locate elements by text?
If so, maybe it would be helpful to get the page source and examine the elements there or share it with us.

This one would store page source in reports folder.
`await driver.logPageSource(this.currentTest.title);`
