### ISSUE TITLE
Add capability to retrieve report path

### ISSUE THREAD

**Issue by noumaans** [NativeScript/nativescript-dev-appium#107]
Currently there is no mechanism to retrieve report path where screenshots and logs are captured.

It is useful to attach screenshots of failures in an HTML report, and path to the failed png file is required for this.

Would suggest adding a method to get _logPath if that would be acceptable to NS Team.

**Comment by noumaans** [comment]
Added PR #108

**Comment by SvetoslavTsenov** [comment]
Already available with next versions of nativescript-dev-appium plugin. 
driver.storageByDeviceName
driver.reportsPath
