### ISSUE TITLE
Issue with image comparison (compareScreen method)

### ISSUE THREAD

**Issue by gkvappium** [NativeScript/nativescript-dev-appium#117]
Steps to reproduce.

1. Do not have any image in the repository.
2. Add a test case for image comparison. 
    assert.isTrue(await driver.compareScreen('HomeScreen',10,10));
3. Check whether resources folder is getting created.

resources->images->application name->phonename->Image-diff.png is not getting created. Basically the resources folder is not getting created after the test run. I am using version 3.2.0 of the plugin

@SvetoslavTsenov @radeva  @vchimev  can you please have a look?

**Comment by vchimev** [comment]
Hey @gkvappium,

I am unable to reproduce such an issue with both versions 3.2.0 and 3.3.0.

If I uncomment [these](https://github.com/NativeScript/nativescript-dev-appium/blob/master/e2e/sample.e2e-spec.ts#L32-L33) lines from the sample test and execute it, I get successfully created `<projectName>/e2e/resources/images/<appName>/<deviceName>/hello-world-41_actual.png` image for both Andorid and iOS.

> Note: at first test execution where no expected images are available, the plugin writes an image with `actual` suffix, not `diff` suffix. As the output mentions:
```
Remove the 'actual' suffix to continue using the image as expected one  /Users/vchimev/Work/tmp/appTs/e2e/resources/images/appTs/Emulator-Api23-Default/hello-world-41.png
```

Could you please elaborate more on any errors in the output log if you still experience the problem as well as the version of NativeScript your app uses?

Thank you,
@vchimev

**Comment by gkvappium** [comment]
Hi @vchimev,

I figured out the problem. Wasn't doing it the right way. I now see <projectName>/e2e/resources/images/<appName>/<deviceName>/hello-world-41_actual.png.

Image comparison test passed after the suffix was removed and when there was an actual image to compare with.

Have one situation though. App name keeps changing for both android and IOS since version number is included in the build. How do I take care of this problem since when I pick up the build from Jenkins, each time the app name is different for both android and iOS.

Thanks

**Comment by SvetoslavTsenov** [comment]
Hi @gkvappium, all compare images methods return boolean result. Basically, you can use the result from comparison and assert image by image or save it and assert all images at the end of test execution.
`
const imageComparissonResult = await comareScreen()

assert.true(imageComparissonResult)`
