### ISSUE TITLE
Handling multiple test case files that are product specific

### ISSUE THREAD

**Issue by gkvappium** [NativeScript/nativescript-dev-appium#119]
Hi ,

Our app supports multiple BT products. I want to have product specific test cases under each relevant subfolder and not e2e, something like

e2e
               ├── Product1
                       ├── testcasefile1.ts
                       ├── testcasefile2.ts ....
               ├── Product2
                      ├── testcasefile1.ts
                      ├── testcasefile2.ts ....

All the products inherit the elements from the same page object files which is not a problem

What are the changes that needs to be done in order to achieve this? Something in mocha.opts and package.json needs to be modified?

@SvetoslavTsenov @vchimev , can you please advice

**Comment by SvetoslavTsenov** [comment]
We have something similar for our nativescript-angular tests here:
https://github.com/NativeScript/nativescript-angular/tree/master/e2e

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov,

Which folder are you referring to? Whichever folder I see in that link, there is only 1 e2e folder with test Case files in that. My requirement seems to be different.

**Comment by gkvappium** [comment]
@SvetoslavTsenov ,

In my case, there is only one code base .There are no different projects as such. Just that the test case files are different for different bluetooth devices . There is only one app that supports multiple devices. Screen changes dynamically based on the connected headset

**Comment by gkvappium** [comment]
Resolved the problem. Closing the issue
