### ISSUE TITLE
Beginning of test execution is extremely slow. Takes 5-6 mins to start off

### ISSUE THREAD

**Issue by gkvappium** [NativeScript/nativescript-dev-appium#121]
I see this issue for both android and ios. Haven't seen this issue earlier. When I kickstart the execution, I see something like 

Timeout expired, output not detected for: /listener started/
Timeout expired, output not detected for: /listener started/
Timeout expired, output not detected for: /listener started/
Timeout expired, output not detected for: /listener started/

After 4-5 attempts, the execution begins. This whole process takes about 6-7 minutes.

I am using version 3.2.0 of the plugin. Appium version is 1.8.0

@SvetoslavTsenov @vchimev

**Comment by gkvappium** [comment]
@SvetoslavTsenov @vchimev ,

Any help in addressing this issue is appreciated. Execution gets bogged down by atleast 10 minutes

**Comment by SvetoslavTsenov** [comment]
Probably because the port is already in use and we are trying to find a port or something like this. I can suggest you to kill all node processes and switch to nativescript-dev-appium@next version which has improved support for appium@1.8.0

**Comment by SvetoslavTsenov** [comment]
Hi @gkvappium, the short answer is yes and it will be great to test it on your side and give us a feedback.

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov ,

I think the problem is with the quit driver instance (At least on windows). When I run the taskkill /im node.exe /F, there are whole lot of running processes that are killed indicating that the close driver isn't working. This is possibly because the command has to be run as an administrator (From /system32 ) that doesn't happen from the plugin close driver

The plugin also throws a warning, Killing simulator with udid undefined. taskkill is not recognised as an internal or external command

**Comment by gkvappium** [comment]
And also we have about 8 test case files. Each file opens a driver instance and then tries to close. If close isn't working the way it should, the port is busy during the next run and then the delay of about 10 minutes to latch onto a port that is free.

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov @vchimev ,

I figured out the problem. This was mainly because of the multiple directories having different test case files. having one common setup.ts file resolves this issue. There were quite a few ports that were getting opened but not getting closed since each folder had this setup.ts file. So the subsequent attempts to trigger a run was always causing a delay since the port it tries to attach to is busy which was causing a delay of close to 10 minutes.

I'll close the issue
