### ISSUE TITLE
Testapp crahses immediately

### ISSUE THREAD

**Issue by p-3** [NativeScript/nativescript-dev-appium#134]
When I am trying to launch Appium tests my apps crashes immediately, and all the tests fails. I got same issue with al my NativeScript projects. The apps is working perfectly without Appium.

Any clue why this is failing on my machine? I am using latest version of Appium, NativeScript etc.

I guessing that the issue is related to

[XCUITest] *********************************
[XCUITest] Simulator architecture appears to be unsupported by the '/var/folders/hx/780t299j5gx89t6kq68g14ph0000gn/T/2018610-6927-10hch85.agyc/Payload/dialogapp.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
[XCUITest] Don't be surprised if the application fails to launch.
[XCUITest] *********************************

But I don’t know how to fix this? See also the full logs :

> tsc -p e2e && mocha --opts ./e2e/config/mocha.opts "--runType" "sim.iPhoneX.iOS114" "--verbose"

Application full path: platforms/ios/build/device/dialogapp.ipa
Using project-local Appium binary.

Device is already started IOSDevice {
  _name: 'iPhone X',
  _apiLevel: '11.4',
  _type: 'simulator',
  _platform: 'ios',
  _token: '3DB7CB27-61DF-4AAE-A64F-6BFF2D66B290',
  _status: 'booted',
  _pid: undefined,
  _startedAt: -1,
  _busySince: -1,
  _config: { density: 3, offsetPixels: 87 } }
''
Application is successfully installed!
Starting server...
[Appium] Welcome to Appium v1.8.1 (REV 7b86146c6064147c4b4f07b4453d25a1ec89950b)

[Appium] Non-default server args:

[Appium]   port: 8300

Timeout expired, output not detected for: /listener started/
[Appium] Welcome to Appium v1.8.1 (REV 7b86146c6064147c4b4f07b4453d25a1ec89950b)

[Appium] Non-default server args:

[Appium]   port: 8310

Timeout expired, output not detected for: /listener started/
[Appium] Welcome to Appium v1.8.1 (REV 7b86146c6064147c4b4f07b4453d25a1ec89950b)

[Appium] Non-default server args:

[Appium]   port: 8320

[Appium] Appium REST http interface listener started on 0.0.0.0:8320

  dialog test
Creating driver!
args.appiumCaps['wdaLocalPort']: undefined
 > undefinedundefined 
 > undefined/session undefined
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"platformName":"iOS","platformVersion":"11.4","deviceName":"iPhone X","noReset":true,"fullReset":false,"app":"platforms/ios/build/device/dialogapp.ipa","udid":"3DB7CB27-61DF-4AAE-A64F-6BFF2D66B290","useNewWDA":false,"wdaStartupRetries":5,"shouldUseSingletonTestManager":false}}

[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","platformVersion":"11.4","deviceName":"iPhone X","noReset":true,"fullReset":false,"app":"platforms/ios/build/device/dialogapp.ipa","udid":"3DB7CB27-61DF-4AAE-A64F-6BFF2D66B290","useNewWDA":false,"wdaStartupRetries":5,"shouldUseSingletonTestManager":false},null,null]

[debug] [BaseDriver] Event 'newSessionRequested' logged at 1531249022602 (20:57:02 GMT+0200 (CEST))

[Appium] Requested iOS support with version >= 10, using 'xcuitest' driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.

[Appium] Creating new XCUITestDriver (v2.84.0) session

[Appium] Capabilities:

[Appium]   platformName: iOS

[Appium]   platformVersion: 11.4

[Appium]   deviceName: iPhone X

[Appium]   noReset: true

[Appium]   fullReset: false

[Appium]   app: platforms/ios/build/device/dialogapp.ipa
[Appium]   udid: 3DB7CB27-61DF-4AAE-A64F-6BFF2D66B290

[Appium]   useNewWDA: false

[Appium]   wdaStartupRetries: 5

[Appium]   shouldUseSingletonTestManager: false

[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"platformName":"iOS","plat...

[BaseDriver] Session created with session id: aba2809a-19db-43c2-bd79-ede4bff93dee

[debug] [XCUITest] Current user: 'p-3'

[debug] [XCUITest] Xcode version set to '9.4.1' 

[debug] [XCUITest] iOS SDK Version set to '11.4'

[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1531249023238 (20:57:03 GMT+0200 (CEST))

[iOSSim] Constructing iOS simulator for Xcode version 9.4.1 with udid '3DB7CB27-61DF-4AAE-A64F-6BFF2D66B290'

[XCUITest] Determining device to run tests on: udid: '3DB7CB27-61DF-4AAE-A64F-6BFF2D66B290', real device: false

[BaseDriver] Using local app 'platforms/ios/build/device/dialogapp.ipa'

[debug] [BaseDriver] Copying local zip to tmp dir

[BaseDriver] Unzipping local app '/var/folders/hx/780t299j5gx89t6kq68g14ph0000gn/T/2018610-7119-13r443l.vnp9/appium-app.zip'...

[debug] [BaseDriver] Unzipping /var/folders/hx/780t299j5gx89t6kq68g14ph0000gn/T/2018610-7119-13r443l.vnp9/appium-app.zip

[debug] [BaseDriver] Testing zip archive: /var/folders/hx/780t299j5gx89t6kq68g14ph0000gn/T/2018610-7119-13r443l.vnp9/appium-app.zip

[BaseDriver] Unzipped local app to '/var/folders/hx/780t299j5gx89t6kq68g14ph0000gn/T/2018610-7119-13r443l.vnp9/Payload/dialogapp.app'

[debug] [BaseDriver] Event 'appConfigured' logged at 1531249034701 (20:57:14 GMT+0200 (CEST))

[debug] [XCUITest] Checking whether app '/var/folders/hx/780t299j5gx89t6kq68g14ph0000gn/T/2018610-7119-13r443l.vnp9/Payload/dialogapp.app' is actually present on file system

[debug] [XCUITest] App is present

[debug] [iOS] Getting bundle ID from app '/var/folders/hx/780t299j5gx89t6kq68g14ph0000gn/T/2018610-7119-13r443l.vnp9/Payload/dialogapp.app': 'com.propal.dialog'

[debug] [BaseDriver] Event 'resetStarted' logged at 1531249034716 (20:57:14 GMT+0200 (CEST))

[debug] [XCUITest] Reset: noReset is on. Leaving simulator as is

[debug] [BaseDriver] Event 'resetComplete' logged at 1531249034717 (20:57:14 GMT+0200 (CEST))

[debug] [XCUITest] Starting log capture for iOS Simulator with udid '3DB7CB27-61DF-4AAE-A64F-6BFF2D66B290', using 'xcrun simctl spawn 3DB7CB27-61DF-4AAE-A64F-6BFF2D66B290 log stream --style compact'

[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1531249035478 (20:57:15 GMT+0200 (CEST))

[XCUITest] Setting up simulator

[debug] [iOS] No reason to set locale

[debug] [iOS] No iOS / app preferences to set

[debug] [iOSSim] Matched 1 Simulator cache item for cleanup: /Users/p-3/Library/Developer/CoreSimulator/Devices/3DB7CB27-61DF-4AAE-A64F-6BFF2D66B290/data/Library/Caches/com.apple.mobile.installd.staging

[debug] [iOSSim] Setting preferences of 3DB7CB27-61DF-4AAE-A64F-6BFF2D66B290 Simulator to {"ConnectHardwareKeyboard":false}

[debug] [iOSSim] Setting common Simulator preferences to {"ConnectHardwareKeyboard":false}

[debug] [iOSSim] Updated 3DB7CB27-61DF-4AAE-A64F-6BFF2D66B290 Simulator preferences at '/Users/p-3/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"3DB7CB27-61DF-4AAE-A64F-6BFF2D66B290":{"ConnectHardwareKeyboard":false}},"ConnectHardwareKeyboard":false}

[debug] [iOSSim] The count of running Simulator UI client instances is 1

[iOSSim] Both Simulator with UDID 3DB7CB27-61DF-4AAE-A64F-6BFF2D66B290 and the UI client are currently running

[debug] [BaseDriver] Event 'simStarted' logged at 1531249035959 (20:57:15 GMT+0200 (CEST))

[debug] [XCUITest] Verifying application platform

[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]

[XCUITest] *********************************

[XCUITest] Simulator architecture appears to be unsupported by the '/var/folders/hx/780t299j5gx89t6kq68g14ph0000gn/T/2018610-7119-13r443l.vnp9/Payload/dialogapp.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.

[XCUITest] Don't be surprised if the application fails to launch.

[XCUITest] *********************************

[debug] [XCUITest] App 'com.propal.dialog' is already installed. No need to reinstall.

[debug] [BaseDriver] Event 'appInstalled' logged at 1531249036241 (20:57:16 GMT+0200 (CEST))

[XCUITest] Using WDA path: '/Users/p-3/Projects/dialog-app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'

[XCUITest] Using WDA agent: '/Users/p-3/Projects/dialog-app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'

[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found

[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body

[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.4\",\n      \"sdkVersion\" : \"11.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.4\",\n      \"ip\" : \"10.10.10.127\"\n    },\n    \"build\" : {\n      \"time\" : \"Jul 10 2018 20:24:06\"\n    }\n  },\n  \"sessionId\" : \"0A24E0E2-1A7A-4919-9847-D2BC2ACA6CEA\",\n  \"status\" : 0\n}"

[XCUITest] Will reuse previously cached WDA instance at 'http://localhost:8100/'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.

[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1531249036386 (20:57:16 GMT+0200 (CEST))

[XCUITest] Using provided WebdriverAgent at 'http://localhost:8100/'

[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1531249036388 (20:57:16 GMT+0200 (CEST))

[debug] [XCUITest] Sending createSession command to WDA

[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body

[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.4\",\n      \"sdkVersion\" : \"11.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.4\",\n      \"ip\" : \"10.10.10.127\"\n    },\n    \"build\" : {\n      \"time\" : \"Jul 10 2018 20:24:06\"\n    }\n  },\n  \"sessionId\" : \"0A24E0E2-1A7A-4919-9847-D2BC2ACA6CEA\",\n  \"status\" : 0\n}"

[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.propal.dialog","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}

    1) "before all" hook
    2) "after all" hook

stop server
Killing simulator with udid 3DB7CB27-61DF-4AAE-A64F-6BFF2D66B290
Stopping server...
Shut down!!!
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1531249204086 (21:00:04 GMT+0200 (CEST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.propal.dialog","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1531249205095 (21:00:05 GMT+0200 (CEST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.propal.dialog","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1531249206102 (21:00:06 GMT+0200 (CEST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.propal.dialog","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1531249207106 (21:00:07 GMT+0200 (CEST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.propal.dialog","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1531249208111 (21:00:08 GMT+0200 (CEST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.propal.dialog","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1531249209116 (21:00:09 GMT+0200 (CEST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.propal.dialog","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1531249210121 (21:00:10 GMT+0200 (CEST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.propal.dialog","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1531249211128 (21:00:11 GMT+0200 (CEST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.propal.dialog","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1531249212134 (21:00:12 GMT+0200 (CEST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.propal.dialog","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1531249213141 (21:00:13 GMT+0200 (CEST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.propal.dialog","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1531249214149 (21:00:14 GMT+0200 (CEST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.propal.dialog","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
[debug] [XCUITest] Failed to create WDA session. Retrying...

Appium terminated due signal: SIGKILL and code: null
Appium terminated due signal: SIGKILL and code: null

  0 passing (5m)
  2 failing

  1) dialog test "before all" hook:
     Error: Timeout of 180000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  2) dialog test "after all" hook:
     TypeError: Cannot read property 'quit' of undefined
      at Object.<anonymous> (e2e/sample.e2e-spec.js:19:22)
      at Generator.next (<anonymous>)
      at e2e/sample.e2e-spec.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (e2e/sample.e2e-spec.js:3:12)
      at Context.after (e2e/sample.e2e-spec.js:18:17)

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! dialog@1.0.0 e2e: `tsc -p e2e && mocha --opts ./e2e/config/mocha.opts "--runType" "sim.iPhoneX.iOS114" "--verbose"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the dialog@1.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/p-3/.npm/_logs/2018-07-10T19_00_14_602Z-debug.log

**Comment by SvetoslavTsenov** [comment]
Hey @p-3, as far as I can see the wda session has failed to be created. Can you please confirm that you have installed all dependencies that appium requires from [here](https://github.com/NativeScript/nativescript-dev-appium). A possible problem could be also something related to unavailable ports. 

1.  Could you execute from terminal 'killall node' processes before retrying executing tests?
2. Increase timeout in mocha options
3. You can also add --reuseDevice option so that the plugin will keep the emulator alive.

Let me know how it goes.

**Comment by p-3** [comment]
-reuseDevice did the trick.

Thanx. 😎
