### ISSUE TITLE
Unwanted Instruments.trace files when running specs

### ISSUE THREAD

**Issue by kamok** [NativeScript/nativescript-dev-appium#139]
### Which platform(s) does your issue occur on?
ios, emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) `4.1.0`
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
```
    "tns-ios": {
      "version": "4.1.0"
    },
    "tns-android": {
      "version": "4.1.3"
    }
```
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

Anytime I run `npm run e2e -- --runType <my-capability>` with iOS, Instruments keep logging their .trace onto my directory.

```
> @ e2e /Users/kamok/code/organizing-mobile/MyApp
> tsc -p e2e && mocha --opts ./e2e/config/mocha.opts "--runType" "sim.iPhone6"

Capabilities found at: /Users/kamok/code/my-app/MyApp/e2e/config/appium.capabilities.json
Appium will use default automation name
Available applications: [ 'platforms/ios/build/emulator/MyApp.app' ]
Application full path: platforms/ios/build/emulator/MyApp.app


instruments[51407]: Template specified: file:///Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Resources/templates/Blank.tracetemplate

instruments[51407]: Waiting for device to boot...

instruments[51407]: Loading template 'file:///Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Resources/templates/Blank.tracetemplate'

Instruments Trace Complete: /Users/kamok/code/organizing-mobile/InternalOrganizing/instrumentscli0.trace
```
### Is there any code involved? 
I replicate this on the demo apps you guys put out, and they have the same behavior. I looked around on the Appium docs and there are options you can apply to disable these logs. But I can't seem to access them with this cli.

**Comment by SvetoslavTsenov** [comment]
Fix released with nativescript-dev-appium@4.0.7
