### ISSUE TITLE
No Config or Sample Test Files created after Appium Installation for JavaScript

### ISSUE THREAD

**Issue by BMwanza** [NativeScript/nativescript-dev-appium#140]
Hi, I am trying to set up my e2e tests using Appium for my NativeScript App, after following the set up guides, I was expecting to see the sample test and the appium config folder but I didn't get anything.

**Comment by SvetoslavTsenov** [comment]
Hej @BMwanza, unfortunately, we still don't provide template-setup for JS tests but only for typescript. Anyway, the good news is that you can create a typescript project and copy setup from it to your JavaScript project of course with a few changes or just have a look in this [repo ](https://github.com/NativeScript/nativescript-sdk-examples-js/tree/svetoslavtsenov/e2e/e2e) where I just added some smoke test for JS.

**Comment by BMwanza** [comment]
Thank you so much @SvetoslavTsenov this is very helpful, I will try to implement the tests, I do have another question regarding the Appium tests: Is it possible, to start a test from a specific page of the native script app?

**Comment by SvetoslavTsenov** [comment]
Hey @BMwanza, I am glad to hear that I helped you. About the second question it is possible but still not implemented in the plugin by default. Basically you will need to implement it by your own. Here is an implementation how to setup [deep link navigation](https://github.com/NativeScript/nativescript-sdk-examples-js/commit/e560f25056797c835329b6835d0b37da3d1e50d5) in your application.

And here is the code how to start the page:

`Starting iOS app ->xcrun simctl openurl booted examplesgo://org.nativescript.nativescriptsdkexamplesng?gotoexample=button/tap-event

Starting Android app ->am start -a android.intent.action.VIEW -d "examplesgo://ng?gotoexample=button/tap-event" org.nativescript.nativescriptsdkexamplesng`

Again, nativescript-dev-appium plugin does not provide functionality to execute adb commands etc. but provides device information (like token which is equal to uidid). 

Let me know if you need further assistance. May be it would be better if you open a new issue on the matter.
