### ISSUE TITLE
Running test suites in real devices

### ISSUE THREAD

**Issue by SuperMarioPunk** [NativeScript/nativescript-dev-appium#149]
It would be great if we could run the e2e test suites on real devices, or there is a way to configure the appium capabilities to do that?

I already runned the apk in my device using the appium desktop, and Nativescript recognizes the device as "connected", but when I run the e2e script appium doesn't found it.

**Comment by SvetoslavTsenov** [comment]
Hi @SuperMarioPunk, indeed you should be able to execute your tests on real devices as well. Could you please share the log from execution as well as you  appium caps?

**Comment by DawidGa** [comment]
Hi, I have the same problem. My real android device is listed in `adb devices` list. However when trying to run `npm run e2e -- --runType android-device-sony` I'm getting error "No such device android-device-sony!!!", and available devices list in logs showing me only emulators configured in Android studio. My current config in capabilities is:
`    "android-device-sony": {
        "platformName": "Android",
        "platformVersion": "6.0",
        "deviceName": "android-device-sony",
        "udid": "RQ3002VLL0",
        "noReset": true,
        "fullReset": false,
        "app": ""
    },`

**Comment by SvetoslavTsenov** [comment]
Hey @DawidGa , I think than your problem is related no noReset option which  should set to false in order appium to install the application. Also, when udid is provided I think you don't need to pass platformVersion option.

**Comment by SvetoslavTsenov** [comment]
I am happy to announce that we have just released nativescript-dev-appium@5.0.0. I hope the logs will be more clearer what is happening under the hood and let me know if you still experience some issues.
