### ISSUE TITLE
tapCenter method params not defined/missing

### ISSUE THREAD

**Issue by skhye05** [NativeScript/nativescript-dev-appium#155]
Hi, 

I am trying to a specific point but I cannot do so because when I try to pass my point axis i getting an error when i check the `ui-element.d.ts` file  i saw the following:

```typescript
    /**
    * Click a point by providing coordinates
    * @param x
    * @param y
    */
    tapCenter(): Promise<void>;
```
the x and y params are missing from the method.

**Comment by SvetoslavTsenov** [comment]
Hey @skhye05, this method  has a wrong signature and doesn't accept any params.
If you need to tap on specific coordinates you need to use 
await driver.clickPoint(x,y)

I hope this helps. Let me know if you have some further issues!
