### ISSUE TITLE
Can you debug with Appium Desktop?

### ISSUE THREAD

**Issue by kamok** [NativeScript/nativescript-dev-appium#17]
I'm using the README parameters, but when I come to do a spec like this:

```
  it('should work', () => {
        return driver
            .elementById("submit-button")
                .should.eventually.exist
    });
```

It's giving me element not found. So I look at tools with Appium that actually lets you see what's being rendered , and I found Appium Desktop. 

However, from using it, it seems that the server instance that is started by `npm run appium` must stay alive for you to "hook" the instance? 

Any ideas? Both using Appium Desktop or debugging in general. I see the login page and buttons on the simulator for a split second, no idea what to do.

**Comment by jeremypele** [comment]
Couldn't make it work too. Would be interested in any solution

**Comment by SvetoslavTsenov** [comment]
Hi, @kamok. I can suggest you try our next version. There is an AppiumDriver class that provides some extended methods which help easier to locate elements like: 
The code is written with typescript so if you are using plain javascript I will try to provide you later an example with plain JS.

`
import { AppiumDriver, SearchOptions, createDriver } from "nativescript-dev-appium";
import { assert } from "chai";

describe("animations", function () {
    let driver: AppiumDriver;
    const externalBtnText = "External animation";
    const selectorBtnText = "Selector";

    before(async () => {
        driver = await createDriver();
    });
   after(async () => {
        await driver.quit();
    });
await driver.findElementByText("some text", SearchOptions.contains);
const random = await driver.findElementByText("random", SearchOptions.contains);
(await random.location())
`
to use the wd you will need to use driver.driver

We are about to release a newer version of the plugin with image support, and much more extended methods which will provide an easier way to locate and interact with elements.

To debug the tests I personally use VS code and that is how my launch.json looks like 

{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Mocha Tests",
            "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
            "args": [
                "-u",
                "tdd",
                "--timeout",
                "999999",
                "--colors",
                "--opts" ,"./e2e/config/mocha.opts",
                "--runType", "sim.iPhone7.ios100"
            ],
            "internalConsoleOptions": "openOnSessionStart"
        }
    ]
}

On the other hand, I will recommend you to use waitForElementById which will ensure you at least that the element is loaded before trying to do further execution steps.

**Comment by jeremypele** [comment]
Just for complements on the accessibility accessors, as I never could plug the appium desktop inspector : https://www.nativescript.org/blog/app-accessibility-in-nativescript

`<Label automationText="myId"></Label>`

then use `await driver.findElementByAccessibilityId('myId', 10000)`

(May be useful for someone passing by, wish I knew that before..)
