### ISSUE TITLE
Android WebView Selector is incorrect

### ISSUE THREAD

**Issue by interrobrian** [NativeScript/nativescript-dev-appium#171]
The Locator class incorrectly translates the class name for "webview" to "android.widget.webView" on Android. According to the [Nativescript docs](https://docs.nativescript.org/ui/ns-ui-widgets/web-view), a web view is "android.webkit.WebView" - note that it's "webkit" and not "widget". I have verified the class name "android.webkit.WebView" the Appium inspector and using the `findElementByClassName` function. I have created a PR to fix this here: #169

**Comment by SvetoslavTsenov** [comment]
Thank again for the PR. It is already merged and will be released in next few days with nativescript-dev-appium@5.0.0
