### ISSUE TITLE
nativescript-appium 

### ISSUE THREAD

**Issue by selvamrajesh** [NativeScript/nativescript-dev-appium#177]
while I try to run the command it shows to error its given below I tried but I can't understand it.can anyone explain about this bug

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'e2e',
1 verbose cli   '--',
1 verbose cli   '--runType',
1 verbose cli   'android19',
1 verbose cli   '--reuseDevice' ]
2 info using npm@6.4.1
3 info using node@v6.4.0
4 verbose run-script [ 'pree2e', 'e2e', 'poste2e' ]
5 info lifecycle @~pree2e: @
6 info lifecycle @~e2e: @
7 verbose lifecycle @~e2e: unsafe-perm in lifecycle true
8 verbose lifecycle @~e2e: PATH: C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Project\JavaScriptApp\node_modules\.bin;C:\Program Files (x86)\Java\jdk1.8.0_131\bin;D:\App\sdk\platform-tools;D:\App\sdk\tools\bin;C:\Program Files\nodejs\;D:\App\sdk\platform-tools;D:\App\sdk\tools;C:\Python27\;C:\Windows\System32;C:\Users\admin\AppData\Roaming\npm
9 verbose lifecycle @~e2e: CWD: D:\Project\JavaScriptApp
10 silly lifecycle @~e2e: Args: [ '/d /s /c',
10 silly lifecycle   'mocha --opts ../config/mocha.opts --recursive e2e --appiumCapsLocation ../config/appium.capabilities.json "--runType" "android19" "--reuseDevice"' ]
11 silly lifecycle @~e2e: Returned: code: 1  signal: null
12 info lifecycle @~e2e: Failed to exec e2e script
13 verbose stack Error: @ e2e: `mocha --opts ../config/mocha.opts --recursive e2e --appiumCapsLocation ../config/appium.capabilities.json "--runType" "android19" "--reuseDevice"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:852:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
14 verbose pkgid @
15 verbose cwd D:\Project\JavaScriptApp
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "e2e" "--" "--runType" "android19" "--reuseDevice"
18 verbose node v6.4.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @ e2e: `mocha --opts ../config/mocha.opts --recursive e2e --appiumCapsLocation ../config/appium.capabilities.json "--runType" "android19" "--reuseDevice"`
22 error Exit status 1
23 error Failed at the @ e2e script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by SvetoslavTsenov** [comment]
Hey @selvamrajesh, could you please provide more info about the command that is used. My guess is that it is missed '--' before --runType.  
For example:
`npm run e2e -- --runType android23`
