### ISSUE TITLE
Lack of documentation for @next, but project management (issues) is centered around it

### ISSUE THREAD

**Issue by Fedelaus** [NativeScript/nativescript-dev-appium#178]
I'm attempting to use this within an nativescript-angular, shared project.

I've come across this issue:
https://github.com/NativeScript/nativescript-dev-appium/issues/31#issuecomment-427071436

This issue has been closed as it's considered fixed by the @next build, but the documentation does not exist for this build, and it appears @next has different scripts and expectations than the current master/npm published repo does.

If issues are being closed as the functionality exists within @next, then ideally the documentation should also center around that.

How do I execute the suite with `@next`? `npm run e2e-appium` complains at a lack of `--runDevice` and I can't see how I can pass this.

**Comment by SvetoslavTsenov** [comment]
Hey @Fedelaus, thank you for provided feedback! I will try to provide more information and a better release cycle soon.

**Comment by SvetoslavTsenov** [comment]
I am happy to announce that we just release nativescript-dev-appium@5.0.0
with changelog and etc. My goal is to release it more often with patch versions than using next. 
Please let me know if you still experience some issues.
