### ISSUE TITLE
How do you change the port for appium server?

### ISSUE THREAD

**Issue by kamok** [NativeScript/nativescript-dev-appium#18]
Setting the env var doesn't work. 

```
    var localServerConfig = {
        host: "localhost",
        port: process.env.APPIUM_PORT || 4723
    };
```

Idk why but it's using 9200 which is elastic search port. 

`printenv` doesn't even show `APPIUM_PORT`

**Comment by SvetoslavTsenov** [comment]
Hi, @kamok. Sorry for delayed report. If you are using our next version you will need to pass and argument from CLI like --port 9090 or by initializing the server to pass the port in the constructor like 

`import { startServer, stopServer } from "nativescript-dev-appium";

before("setup server", async () => {
    return await startServer(1234);
});

after("kill server", async () => {
    return await stopServer();
});`

Have in mind that we are about to release a newer version with a bunch of new features like image processing and etc.
