### ISSUE TITLE
Specify custom remote url

### ISSUE THREAD

**Issue by chevallard** [NativeScript/nativescript-dev-appium#195]
I'm trying to integrate this plugin with SauceLabs or BrowserStack real device testing. Would it be possible to add the ability to specify a custom remote url for the driver to use?

**Comment by SvetoslavTsenov** [comment]
Hey, @chevallard [here is a section](https://www.nativescript.org/blog/start-testing-your-nativescript-apps-properly) explaining how to use nativescript-dev-appium plugin in SauceLabs. Could you please check it out and come back to me it is not the one you are searching for.

**Comment by chevallard** [comment]
The endpoint for SauceLabs in the AppiumDriver for this project is hardcoded to point to https://ondemand.saucelabs.com:443/wd/hub, which only allows for testing on emulators. 

To test on real devices, the endpoint is https://us1.appium.testobject.com/wd/hub (for the US server, as seen here: https://wiki.saucelabs.com/display/DOCS/Appium+Testing+on+Real+Devices)

But ideally, I'd like to be able to specify any remote endpoint. My team already uses BrowserStack for their manual device testing, and I'd like to be able to use their automated testing endpoint with this plugin.

**Comment by SvetoslavTsenov** [comment]
Thanks for the detailed information. I will try to provide a new version of the plugin where it would be able to specify a custom endpoint.

**Comment by chevallard** [comment]
Thank you for implementing this so quickly!
