### ISSUE TITLE
Support for isSelected

### ISSUE THREAD

**Issue by lohiarahul** [NativeScript/nativescript-dev-appium#199]
Currently there seems to be no Straightforward way to test elements like Switches and Checkboxes. 
Could we have an isSelected() for the same?

http://appium.io/docs/en/commands/element/attributes/selected/

**Comment by SvetoslavTsenov** [comment]
Hey @lohiarahul, the good news is that it is already available with the latest release of nativescript-dev-appium@5.0.0

**Comment by lohiarahul** [comment]
The isSelected() method tries to do a getAttribute("selected") on the UIElement and that throws an error for not being a valid attribute name. But with this version getAttribute("value") seems to work which returns a string representation of the boolean value

**Comment by SvetoslavTsenov** [comment]
Let me test it on my side but it seems that you are right.
