### ISSUE TITLE
New issue observed with reporting on plugin version 5.0.0

### ISSUE THREAD

**Issue by gkvappium** [NativeScript/nativescript-dev-appium#201]
There seems to be a new issue that has cropped up on Windows platform . No issue with Mac though.

For html reports we use mochawesome (--reporter mochawesome). With plugin 5.0.0, reports are not getting generated . Checked for permission issues as well (By running cmd in admin mode). But nothing seems to resolve the problem. On the same windows machine, when we downgrade the plugin to @3.2.0, mochawesome reports are getting created without any problem. Can't really figure out what's going wrong since there is no error message as such

@SvetoslavTsenov , do you have any clue?

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov , can you please have a look into this?

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov ,

I think there is a problem with async stop() method wherein we stop the appium server (appium-server.ts). There is no problem on mac, but on windows, the stop server doesn't seem to be working the way it should. For testing, I just commented the stop() method and I saw that the reports were getting generated. But the strange thing is , this issue is seen on 5.0.0. but not on 3.2.0.

**Comment by SvetoslavTsenov** [comment]
Hi @gkvappium, thank you for detailed information. I will try to investigate the issue since there is a small change in dispose methods and could be caused by me.

**Comment by SvetoslavTsenov** [comment]
Hi @gkvappium I have tested it on my side and everything works fine. Anyway, could you please provide all deps and versions that you are currently using, Appium capabilities config and mocha options

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov ,

Dependencies are,

    "dependencies": {
    "app-root-path": "^2.0.1",
    "blink-diff": "^1.0.13",
    "chai": "~4.1.1",
    "chai-as-promised": "~7.1.1",
    "frame-comparer": "^2.0.1",
    "glob": "*",
    "mocha": "~5.2.0",
    "mocha-junit-reporter": "^1.18.0",
    "mocha-multi": "^1.0.1",
    "nativescript-theme-core": "~1.0.2",
    "tns-core-modules": "~3.3.0",
    "wd": "^1.11.1",
    "webdriverio": "^5.6.2",
    "yargs": "^8.0.2"
  },
  "devDependencies": {
    "@types/chai": "^4.0.2",
    "@types/mocha": "^2.2.41",
    "@types/node": "^7.0.5",
    "@types/webdriverio": "~4.8.4",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "mobile-devices-controller": "^2.0.1",
    "mochawesome": "^3.0.0",
    "mochawesome-report-generator": "^3.0.1",
    "nativescript-dev-appium": "~5.0.0",
    "nativescript-dev-typescript": "~0.5.0",
    "python-shell": "^0.5.0",
    "request": "^2.88.0",
    "shell-helper": "^1.0.2",
    "should": "^13.2.3",
    "synchronisify": "^0.9.2",
    "typescript": "~2.4.2"

One of the capabilities is ,

    "android26": {
        "platformName": "Android",
        "platformVersion": "8.0.0",
        "deviceName": "Galaxy S8",
        "autoGrantPermissions": true,
        "lt": 60000,
        "appPackage": "com.xxxxxxx.control",
        "newCommandTimeout": 720,
        "noReset": true,
        "automationName": "uiautomator2",
        "fullReset": false,
        "app": "e2e/Android_apk/app.apk"
    },

mocha.opts 

    --reporter mochawesome 
--reporter-options timestamp,code=true,spec=-,mocha-junit-reporter=test-results.xml

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov ,

I resolved this issue. I just updated some dependencies in package.json. It got resolved. Reports are getting generated. Thanks for looking into this though :)

**Comment by SvetoslavTsenov** [comment]
I am glad that you manage to solve it. Could you please share which dependency was the one causing the problem with the reporter?

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov ,

        "mochawesome": "^3.1.1",
        "mochawesome-report-generator": "^3.1.5",
I updated these 2.

**Comment by gkvappium** [comment]
Closing since the issue is resolved
