### ISSUE TITLE
Angular jasmine running zero out of zero specs

### ISSUE THREAD

**Issue by wytzen** [NativeScript/nativescript-dev-appium#213]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project:
 - CLI: 5.2.4
 - Cross-platform modules: 5.2.2
 - Android Runtime: 5.2.1
 - iOS Runtime: 5.2.0
 - Plugin(s): nativescript-dev-appium 5.1.0

**Describe the bug**
Running the e2e tests on an angular/jasmine setup does not work out of the box even with a nativescript test project. It will always run zero out of zero tests and then npm will throw an error.

npm run e2e ios

> @ e2e /Users/ /GIT/e2e-test
> node ./node_modules/nativescript-dev-appium/check-dev-deps.js &&  tsc -p e2e  &&  jasmine --config=./e2e/config/jasmine.json  "ios"

Jasmine started

Executed 0 of 0 specs SUCCESS in 0.002 sec.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ e2e: `node ./node_modules/nativescript-dev-appium/check-dev-deps.js &&  tsc -p e2e  &&  jasmine --config=./e2e/config/jasmine.json  "ios"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ /.npm/_logs/2019-04-02T07_21_20_801Z-debug.log

**To Reproduce**
run the following commands:

npm install -g appium
npm install -g ios-deploy
tns create e2e-test --ng
cd e2e-test
npm install -D nativescript-dev-appium (select typescript, select angular)
tns build ios
npm run e2e ios

**Expected behavior**
jasmine will run two tests and still fail but due to different reasons.

**Sample project**
The issue can be recreated with a sample app from nativescript.

tns create e2e-test --ng

**Comment by SvetoslavTsenov** [comment]
Hey @wytzen  I suspect that you have passed the ns-dev-appium options with white space, which  brakes jasmine. 
Please try something like this:
`npm run e2e -- --runType=android23`
Please, notice that I have used '=' not white space.
