### ISSUE TITLE
Test results file creation problem

### ISSUE THREAD

**Issue by daniel-greguric** [NativeScript/nativescript-dev-appium#215]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project:
 - CLI: 5.3.1
 - Android Runtime: 3.4.2.
 - iOS Runtime: 3.4.1.
 - Plugin(s):
mocha: ^6.1.2
mocha-junit-reporter: ^1.21.0
mocha-multi: ^1.0.1

**Describe the bug**
npm run e2e -- --runType android28 does not produce test-results.xml as it should. I came accross several different behaviors:
1. if I don't change reporter options and leave everything as in your demo (--reporter-options spec=-,mocha-junit-reporter=test-results.xml) =>  test-results.xml gets created in root folder on start of test run (it has 0 KB) and it gets deleted when tests end
2. if I update mocha.opts file reporter options line to this "--reporter-options spec=-,mocha-junit-reporter=./res/test-results.xml" => test-results.xml gets created in root/res folder but it has 0 KB (it's empty)
3. Third behavior is not regarding your demo app so I explained it in Additional context section

**To Reproduce**
1. Download demo from https://github.com/NativeScript/ns-dev-days-appium-plugin/tree/master/template-hello-world-ts
2. Install missing stuff untill tns build android works
3. Started Android emulator
4. tns run android --justlaunch
5. npm run e2e -- --runType android28

**Expected behavior**
I expected test-results.xml file would exist after test run is done, in a path set in mocha.opts file and that it would contain test info

**Sample project**
I downloaded demo project from here:
https://github.com/NativeScript/ns-dev-days-appium-plugin/tree/master/template-hello-world-ts
But I'm sending you zipped one too:
[ns-dev-days-appium-plugin-master.zip](https://github.com/NativeScript/nativescript-dev-appium/files/3063983/ns-dev-days-appium-plugin-master.zip)

**Additional context**
I came across this problem on my work project and then tried your demo project and see problem happens there too. Somehow, I succeeded to get correctly filled test-results.xml on my own project, but it definitely is not behaving as it should. In my project, I set reporter options as in case 2 from "To Reproduce" section, to output test-results.xml to a root/res folder and it behaves like this:
1. When test run starts, test-results.xml gets created in root/res folder and it has 0KB
2. When test run ends, test-results.xml in root/res folder gets deleted but another test-results.xml file gets created in root folder and it has all test data. So, I am able to get my test results and publish them on Azure DevOps server, but it behaves weird as I described here and I'm sure this should not work like this.

**Comment by SvetoslavTsenov** [comment]
Hey @daniel-greguric, I will try to investigate the issue these days. 
Meanwhile could try nativescript-dev-appium@next and tell me if you still experience the same issue.
Also if you create a new project and install it using mocha as a testing framework than you could take a look how to use mochawesome reporter which can present diff images and etc.

**Comment by daniel-greguric** [comment]
Hello @SvetoslavTsenov Thank You for the feedback, I will try this when I get some time for it and get back to You here.
