### ISSUE TITLE
Cannot find module 'child_process'

### ISSUE THREAD

**Issue by alexZaicev** [NativeScript/nativescript-dev-appium#223]
tns --version ==> 5.3.1

√ Component tns-android has 5.3.1 version and is up to date.
√ Component tns-ios has 5.3.1 version and is up to date.

**Describe the bug**
Whenever I try to run 'npm run e2e -- --runType android26' command on an opened Pixel XL API 26 emulator I receive an erorr message: 

node_modules/nativescript-dev-appium/lib/appium-server.d.ts:1:30 - error TS2307: Cannot find module 'child_process'.

1 import { ChildProcess } from "child_process";
                               ~~~~~~~~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ e2e: `node ./node_modules/nativescript-dev-appium/check-dev-deps.js &&  tsc -p e2e  &&  mocha --opts ./e2e/config/mocha.opts  "--runType" "android26"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

For the test, I have described a simple scenario to find buttons and labels by text value, and verify that they are not null or undefined.

My package.json dependency: 

  "dependencies": {
    "globals": "^11.9.0",
    "nativescript-appversion": "^1.4.1",
    "nativescript-barcodescanner": "^3.0.0",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-drop-down": "^4.0.1",
    "nativescript-email": "^1.5.3",
    "nativescript-https": "^1.0.3",
    "nativescript-imagepicker": "^6.0.6",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-phone": "^1.4.0",
    "nativescript-plugin-firebase": "^7.6.0",
    "nativescript-pulltorefresh": "^2.2.0",
    "nativescript-ripple": "^2.1.0",
    "nativescript-statusbar": "^5.0.0",
    "nativescript-text-justify": "^1.1.1",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-chart": "^4.0.2",
    "nativescript-ui-sidedrawer": "^5.1.0",
    "nativescript-unit-test-runner": "^0.3.4",
    "nativescript-zxing": "^1.5.8",
    "rxjs": "^6.3.3",
    "tns-core-modules": "^5.3.1"
  },
  "devDependencies": {
    "@types/chai": "~4.1.7",
    "@types/mocha": "^5.2.5",
    "@types/node": "~10.12.18",
    "chai": "4.2.0",
    "g": "^2.0.1",
    "karma": "^4.0.1",
    "karma-chai": "0.1.0",
    "karma-mocha": "1.3.0",
    "karma-nativescript-launcher": "0.4.0",
    "mocha": "5.2.0",
    "mocha-junit-reporter": "~1.18.0",
    "mocha-multi": "~1.0.1",
    "nativescript-dev-appium": "^5.2.0",
    "nativescript-dev-sass": "^1.7.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.21.2",
    "tslint": "^5.12.0"
  }

**Comment by SvetoslavTsenov** [comment]
@alexZaicev  Could try to execute again
`npm i`  
`npm run watch` 
and make sure that the e2e files are transpiled to javascript. It looks like node typings are missing.

**Comment by alexZaicev** [comment]
`npm run watch` failed to execute: npm ERR! missing script: watch. 

`npm run e2e-watch` failed to execute as well, complaining about the same missing package `child_process`. 

I`ve checked if JS files are present, and they are in the e2e package.

**Comment by SvetoslavTsenov** [comment]
Could you try to install @types/node
Or if you could send me the package.json

**Comment by alexZaicev** [comment]
The @types/node are installed.

Package.json dependencies:

`"dependencies": {
"globals": "^11.9.0",
"nativescript-appversion": "^1.4.1",
"nativescript-barcodescanner": "^3.0.0",
"nativescript-checkbox": "^3.0.3",
"nativescript-drop-down": "^4.0.1",
"nativescript-email": "^1.5.3",
"nativescript-https": "^1.0.3",
"nativescript-imagepicker": "^6.0.6",
"nativescript-iqkeyboardmanager": "^1.3.0",
"nativescript-phone": "^1.4.0",
"nativescript-plugin-firebase": "^7.6.0",
"nativescript-pulltorefresh": "^2.2.0",
"nativescript-ripple": "^2.1.0",
"nativescript-statusbar": "^5.0.0",
"nativescript-text-justify": "^1.1.1",
"nativescript-theme-core": "^1.0.4",
"nativescript-ui-chart": "^4.0.2",
"nativescript-ui-sidedrawer": "^5.1.0",
"nativescript-unit-test-runner": "^0.3.4",
"nativescript-zxing": "^1.5.8",
"rxjs": "^6.3.3",
"tns-core-modules": "^5.3.1"
},
"devDependencies": {
"@types/chai": "~4.1.7",
"@types/mocha": "^5.2.5",
"@types/node": "~10.12.18",
"chai": "4.2.0",
"g": "^2.0.1",
"karma": "^4.0.1",
"karma-chai": "0.1.0",
"karma-mocha": "1.3.0",
"karma-nativescript-launcher": "0.4.0",
"mocha": "5.2.0",
"mocha-junit-reporter": "~1.18.0",
"mocha-multi": "~1.0.1",
"nativescript-dev-appium": "^5.2.0",
"nativescript-dev-sass": "^1.7.0",
"nativescript-dev-typescript": "~0.7.0",
"nativescript-dev-webpack": "^0.21.2",
"tslint": "^5.12.0"
}`

**Comment by SvetoslavTsenov** [comment]
Sorry for delayed answer but I was on vacation. 
My guess is that you need to setup .tsconfig file. Can you share it as well?

**Comment by alexZaicev** [comment]
Contents of .tsconfig.json

    {
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "skipLibCheck": true,
        "lib": [
            "es6",
            "dom",
            "es2017"
        ],
        "baseUrl": ".",
        "paths": {
            "~/*": [
                "app/*"
            ],
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
    }

**Comment by Serge-SDL** [comment]
Same issue here!

**Comment by alexZaicev** [comment]
@SvetoslavTsenov will this issue be sorted any time soon?

**Comment by Serge-SDL** [comment]
Hi!
I solved my problem: issue was in tsconfig.json.
- check if your typeRoots option as somthing like "../node_modules/@types" with a correct path
- chek that in node_modules/@Types you have a node folder with a base.d.ts (in this file there is a declare module "child_process" -> that makes the compiler work)
- I had also a types ["jasmine"] in my compilerOptions and needed to remove it to make it works (no idea why)
hope it helps!

**Comment by alexZaicev** [comment]
@Serge-SDL thanks for you advice! However, switched to mocha/chai and it started to work somehow :D Closing issue as the problem was resolved
