### ISSUE TITLE
Nativescript-dev-appium Installation

### ISSUE THREAD

**Issue by johnntupmc** [NativeScript/nativescript-dev-appium#225]
For our project, Front end devs give an apk file to install on the device connected with android bridge. I have appium installed globally. Since, I don't have a dev project opened (just I have apk file), how can I install **nativescript-dev-appium** plugin and subsequently e2e folder, write scripts with typescript. It would be great if someone can give a guidance on this issue. Thanks in advance !!

**Comment by SvetoslavTsenov** [comment]
Hey @johnntupmc, I am not sure that I understand exactly the scenario that you have describe, but if I am right you need a project which will have only e2e tests.
I will suppose you to do a few steps 

1. create a separate node app `npm init` and follow the steps that npm requires.
2. install nativescript-dev-appium `npm i -D nativescript-dev-appium`.
3. `nativescript-dev-appium ` should add e2e folder with some sample tests and config file with setup.
4. run tests using `npm run e2e -- --runType android23 --appPath [path to the application]`.
