### ISSUE TITLE
headless support

### ISSUE THREAD

**Issue by Serge-SDL** [NativeScript/nativescript-dev-appium#226]
Hi!
I'm trying to test my nativescript app on aws cloudbuild, but it requires to launch tests in headless mode. Appium support the feature (https://discuss.appium.io/t/can-i-run-appium-in-headless-mode/3482), but how can I pass the -no-audio -no-window options to nativescript-dev-appium ?
thanks!

**Comment by SvetoslavTsenov** [comment]
Hey @Serge-SDL, I have not tested it personally, I guess you can try 
to set in `appium.capabilities.json` file  to desired device 

`"isHeadless":true`

and to provide an additional option  when you run the tests with 

`npm run e2e -- --runType [desiredRunType] --ignoreDeviceController`


Here is an article that explains all capabilities related to [appium](http://appium.io/docs/en/writing-running-appium/caps/).
