### ISSUE TITLE
How to use the mochawesome reporter that is part of release 5.3.0

### ISSUE THREAD

**Issue by gkvappium** [NativeScript/nativescript-dev-appium#230]
I see that that mochawesome is integrated into 5.3.0. We were installing this separately and creating html reports

Question: How exactly this needs to be included in the test case file? Can the desired capabilities be included in the report by adding context? Can the screenshots also be included in the report in case of failures?

@SvetoslavTsenov , any input on this?

**Comment by SvetoslavTsenov** [comment]
@gkvappium, I would suggest you to create a sample tsc app and install nativescript-dev-appium as you will need to select mocha as a testing framework. This new e2e samples provide information how to use mochawesome reporter.Let me know if need more information.

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov ,

Are you referring to the example here @ https://github.com/NativeScript/nativescript-dev-appium/blob/master/samples/e2e-ts/typescript.mocha.sample.e2e-spec.mochawesome.ts 

We already have a working framework with mocha as the test framework

**Comment by SvetoslavTsenov** [comment]
Basically I suggest you to see the what's new in the provided template from dev-appium and update your tests. 

There are a few major steps 
1. setup.ts

`import { startServer, stopServer, ITestReporter, nsCapabilities, LogImageType } from "nativescript-dev-appium";
const addContext = require("mochawesome/addContext");

const testReporterContext = <ITestReporter>{};
testReporterContext.name = "mochawesome";
testReporterContext.reportDir = "mochawesome-report";
testReporterContext.log = addContext;
nsCapabilities.testReporter = testReporterContext;

before("start server", async function () {
    nsCapabilities.testReporter.context = this;
    await startServer();
});

after("stop server", async function () {
    nsCapabilities.testReporter.context = this;
    await stopServer();
});`

2. Each describe should have a hook like:
`before(async function () {
        nsCapabilities.testReporter.context = this;
        driver = await createDriver();
    });`

3. Make sure that all `()=>` are replaced with `function()` with that said should not be used anonymous functions any longer.

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov ,

Is it possible to add a global context to include something like all the desired capabilities. I want to have this as part of each test case file. I added the context and also got the screenshots in the report. Currently it seems like there is no way to include the additional test contest globally. Any thoughts on this?
