### ISSUE TITLE
Possibility to change appium capabilities for one test

### ISSUE THREAD

**Issue by Serge-SDL** [NativeScript/nativescript-dev-appium#232]
Hi!
I cannot find a way to change capabilities between 2 group of specs. For exemple I need for one of my test to keep app installed, but not for the other ones.

what I need it something like that:
```
            capabilities.setCapability('noReset', true);
            driver = await createDriver();
```

I there already a way, or is it planned ?
thanks!

**Comment by ArmughanALi** [comment]
One Quick way which i know is Skip others and run the test file .

describe.skip('setting scenario', () => {

**Comment by SvetoslavTsenov** [comment]
You can also simply use 

`await driver.driver.removeAppFromDevice('com.example.AppName');`

Basically all commands can be found in [appium docs](http://appium.io/docs/en/commands/device/app/remove-app/)

![Screenshot 2019-08-08 at 13 11 29](https://user-images.githubusercontent.com/3598759/62695010-1ce29380-b9de-11e9-9bda-d08321be9b08.png)
