### ISSUE TITLE
Is Parallel execution supported in Nativescript dev Appium?

### ISSUE THREAD

**Issue by swathiRajaPrasanth** [NativeScript/nativescript-dev-appium#239]
**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SvetoslavTsenov** [comment]
Hey @swathiRajaPrasanth, could  you please explain more specific your vision of parallel execution. I really need a real case scenario so that I can be more specific if the plugin support this scenario or not.

**Comment by klaask** [comment]
Parallel test execution on two android devices connected to the same build server works on our side. We had to use the environment variable "APPIUM_PORT" for different appium ports. In appium.capabilities.json "port" seems to be ignored.
