### ISSUE TITLE
TypeError: Cannot read property 'statBarHeight' of undefined

### ISSUE THREAD

**Issue by setrar** [NativeScript/nativescript-dev-appium#287]
with 

```
$ ns --version                         
7.0.11
```

I am having this issue when testing with NativeScript Appium on MacOS against iOS

![image](https://user-images.githubusercontent.com/123704/101294497-a4643080-37e5-11eb-81d7-85fc97b9d437.png)

The issue seems to be coming from the below source code:

https://github.com/NativeScript/nativescript-dev-appium/blob/8744490b12d95bcd0478ba76f18a7aa60688b1f2/lib/appium-driver.ts#L325

- [ ] appium.capabilities.json file

```json
    "sim.iPhone12": {
        "platformName": "iOS",
        "platformVersion": "/14*/",
        "deviceName": "iPhone 12",
        "bundleId": "org.nativescript.b300098957",
        "noReset": true,
        "fullReset": false,
        "statBarHeight": 0,
        "app": ""
    }
```

- [ ] command running the {N} test

```
$ npm run e2e -- --runType sim.iPhone12
```

What library am I missing?

**Comment by AlbanRicherPro** [comment]
I have the same problem 😕 . 

Did you find a solution?

**Comment by rob4226** [comment]
@AlbanRicherPro @setrar  I also have the same problem.  Any update?

**Comment by belloyang** [comment]
Same issue. 
in the console log, it shows:
```
Session info:  
undefined
Appium settings:  
Current version of appium doesn't support appium settings! 
Appium driver has started successfully!
Something went wrong! Appium driver failed to start. Check appium config file. 
TypeError: Cannot read property 'statBarHeight' of undefined 
```

Session Info is undefined, why is it?

**Comment by vdbongard** [comment]
I had the same error and could solve it by using a different appium port.

You can use the CLI argument `--port` or set an environment variable, either `APPIUM_PORT` or `npm_config_port` work.
The default port is 4723, so I set the env variable APPIUM_PORT to 4724 and it worked again.

Not sure why the default port is not working, there seems to be another instance of appium or another process running.

If I just start appium in the terminal via `$ appium` I get an error: 
```
[HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
Fatal Error: listen EADDRINUSE: address already in use 0.0.0.0:4723
```

With `appium --port 4724` it starts normally.

(I am on Windows 10 btw)

**Comment by Kevonia** [comment]
I have the same problem confused .

Did you find a solution?
