### ISSUE TITLE
How to sendKeys or setValue?

### ISSUE THREAD

**Issue by jordandlaman** [NativeScript/nativescript-dev-appium#30]
I couldn't find any options that doesn't throw a typeError.  I am relatively new to this plugin and couldn't find a ton of chatter on the internet.  Am I missing something or is there some workaround? I was attempting to use a login screen and input credentials.

**Comment by jordandlaman** [comment]
I actually figured this late yesterday.  My code looks something like and it worked.

` const emailFormField = await driver.findElementByText('Email');`
   `const wdElement = await emailFormField.element();`
  `await wdElement.sendKeys('BLAH');`

 Looks like there are no type definitions for the appium javascript bindings which is why my IDE 
 couldn't find any type completions for sendKeys.  I might look into creating them so people can an 
 easier time finding the answer to these sorts of questions.  I had to use the step debugger and look  
 through proto to find the right usage.

**Comment by gkvappium** [comment]
Hi @jordandlaman ,

I am planning to use this helper plugin for E2E tests. Could you please tell me how did you achieve complex gestures ,long_press etc. I do not see any of these methods in the AppiumDriver under /lib of nativescript-dev-appium?
