### ISSUE TITLE
Will this work on the latest TNS version 2.0.1? Also, will it support Angular 2 integration (TypeScript) support?

### ISSUE THREAD

**Issue by Headcult** [NativeScript/nativescript-dev-appium#4]
Good to see an e2e framework for NativeScript.
Will this work on the latest TNS version 2.0.1? Also, will it support Angular 2 integration (TypeScript)?

**Comment by Headcult** [comment]
Also, this is not working with the sample app (42 Taps) as it says, it could not find an element with the given search parameters (even though I added the id attribute to the Button element in the .xml file). Sometimes, it's giving timeout exceeded error.

**Comment by Headcult** [comment]
Any help in dealing with finding the right UI elements when using HTML templates in Angular 2 with NativeScript.

**Comment by hdeshev** [comment]
Ooops, I somehow missed this issue. Yes, the plugin works with the latest TNS and supports Angular apps (it started as a way to implement E2E router tests).

https://github.com/NativeScript/nativescript-angular/blob/master/tests/e2e-tests/multi-page-routing.js
