### ISSUE TITLE
Add ability to block-out area when comparing images

### ISSUE THREAD

**Issue by wvegteren** [NativeScript/nativescript-dev-appium#47]
It would be great if we could block-out some specific areas in an image that should be ignored for comparison. For example, we show a date in the startup screen of our app. By having the ability to block-out the date area we could use `compareImages` to check all relevant parts on the screen.  
Blik-diff already supports 'block-out'.

Thanks,
Winfred

**Comment by SvetoslavTsenov** [comment]
Hey @wvegteren, we have already added this feat with this commit https://github.com/NativeScript/nativescript-dev-appium/commit/9e3e30c98506117d5a2eda9266968adedcf12b55
Please take a look if you have time :)
