### ISSUE TITLE
Something during the PostInstall needs "colors"

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-dev-appium#51]
Just doing a simple: `npm i nativescript-dev-appium --save-dev` causes it to fail to install during your postinstall.js script.   I have no idea what triggers this code path, but if the lib/utils.js is loaded, this fails because colors is being installed as part of the package, but it doesn't already exist.

The ` D:\projects\nativescript\stage-ns\node_modules\nativescript-dev-appium\lib\utils.js:8:1)` has a reference to require('colors')`

Full Error:

```
> node ./postinstall.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\projects\nativescript\stage-ns\node_modules\nativescript-dev-appium\li
b\utils.js:8:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm WARN Error: EPERM: operation not permitted, lstat 'D:\projects\nativescript\stage-ns\node_module
s\url\node_modules'
npm WARN     at Error (native)
npm WARN  { Error: EPERM: operation not permitted, lstat 'D:\projects\nativescript\stage-ns\node_mod
ules\url\node_modules'
npm WARN     at Error (native)
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'lstat',
npm WARN   path: 'D:\\projects\\nativescript\\stage-ns\\node_modules\\url\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-dev-appium@3.0.0 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nativescript-dev-appium@3.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nathanaeland\AppData\Roaming\npm-cache\_logs\2017-10-17T20_16_19_505Z-debug.log
```

Workaround:
`npm i --save-dev colors` then do the install of dev-appium.

**Comment by vchimev** [comment]
Hey @NathanaelA,

Thank you for the report.

I haven't managed to reproduce this error by my side with `nativescript-dev-appium@3.0.0` version. However, it looks like the *colors* dependency is not used anymore, so I opened a pull request to remove it.

In the meantime, the `postinstall` script has been rewritten to plain JavaScript with no dependencies to external modules in https://github.com/NativeScript/nativescript-dev-appium/pull/39. These changes are available with `nativescript-dev-appium@next` version.
