### ISSUE TITLE
Error in the runner when trying to execute the tests on IOS

### ISSUE THREAD

**Issue by gkvappium** [NativeScript/nativescript-dev-appium#58]
Hi,

I see the below error in the logs when I try to run the tests on IOS.

nativescript-dev-appium test$ npm run e2e -- --runType iphone6

> nativescript-dev-appium@3.0.0 e2e /Users/test/node_modules/nativescript-dev-appium
> tsc -p e2e && mocha --opts ./e2e/config/mocha.opts -- "--runType" "iphone6"

Warning: Could not find any test files matching pattern: --runType
Warning: Could not find any test files matching pattern: iphone6
/Users/test/node_modules/nativescript-dev-appium/lib/capabilities-helper.js:16
            throw new Error("Not suitable runType!!!");
            ^

Error: Not suitable runType!!!
    at Object.resolveCapabilities (/Users/test/node_modules/nativescript-dev-appium/lib/capabilities-helper.js:16:19)
    at new NsCapabilities (/Users/test/node_modules/nativescript-dev-appium/lib/ns-capabilities.js:18:50)
    at Object.<anonymous> (/Users/test/node_modules/nativescript-dev-appium/index.js:21:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/test/node_modules/nativescript-dev-appium/e2e/grocery_sample.js:5:33)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /Users/test/node_modules/nativescript-dev-appium/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/test/node_modules/nativescript-dev-appium/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/test/node_modules/nativescript-dev-appium/node_modules/mocha/lib/mocha.js:513:10)
    at Object.<anonymous> (/Users/test/node_modules/nativescript-dev-appium/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1

    at Mocha.loadFiles (/Users/test/node_modules/nativescript-dev-appium/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/test/node_modules/nativescript-dev-appium/node_modules/mocha/lib/mocha.js:513:10)
    at Object.<anonymous> (/Users/test/node_modules/nativescript-dev-appium/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-dev-appium@3.0.0 e2e: `tsc -p e2e && mocha --opts ./e2e/config/mocha.opts -- "--runType" "iphone6"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nativescript-dev-appium@3.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

My configuration seems to be fine. 

"iphone6": {
        "udid": "30cbd11ca498428a9a19e3b4249cb38b8a41ea3d",
        "platformName": "iOS",
        "platformVersion": "11.0.1",
        "deviceName": "iphone 6",
        "noReset": true,
        "fullReset": false,
        "xcodeConfigFile": "/Users/test/dev/captune/bin/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig",
        "automationName": "XCUITest",
        "autoAcceptAlerts": "true",
        "notificationsAuthorized": "true",
        "showXcodeLog": "true",
        "app": "/Users/test/dev/captune/AUT/ios/NSSimpleUI.ipa"

@SvetoslavTsenov can you please have a look into this issue?

**Comment by zbranzov** [comment]
Hi @gkvappium 
I guess you don't have the proper runType in your [capabilities file ](https://github.com/NativeScript/nativescript-dev-appium/blob/master/e2e/config/appium.capabilities.json) as the error says:

> 'Error: Not suitable runType!!!'

More info you can find [here](https://github.com/NativeScript/nativescript-dev-appium#custom-appium-capabilities)

**Comment by gkvappium** [comment]
@zbranzov , I double checked the caps. This is a working desired caps that I already use it for my other setup that I've created based on Python. I have attached it to the ticket as well

**Comment by jordandlaman** [comment]
I have noticed that anytime you are trying to set platformVersion to the exact version it doesn't like that.  So maybe try changing 11.0.1 to 11.0 and see if that works.

**Comment by SvetoslavTsenov** [comment]
Hey @gkvappium, can please send us what is your platform structure as well as which version of plugin do you use. We are going to release a new stable one in next days and I need to test your scenario as well.

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov ,

I use the latest plugin (nativescript-dev-appium@3.0.0)

To isolate the problem, I cloned the demo app from https://github.com/NativeScript/nativescript-dev-appium. I made sure that all the dev dependencies are installed. I have installed appium globally

1. tns doctor said there are no problems.
2. I built the app for both the platforms ios and android. It got built successfully.
3. I changed the capabilities as needed.

Looks like it is hitting the problem in capabilities-helper.js file. Maybe the capabilities cannot be parsed to the appium driver correctly. My entire setup seems to be correct. But I get an error message saying that "Not suitable RunType".

Let me know if you need any logs. On the same machine, I have another framework in python which gets executed on both android and ios without any problem.

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov , Any quick feedback on this is highly appreciated. It's been pending from quite sometime.

Thanks

**Comment by SvetoslavTsenov** [comment]
@gkvappium, I am not sure what causes the problem but for me, there is some mismatch in file paths. Cloud you try the following steps:

1.  Create hellow-world-template using tns create hello-world --tsc 
2.  tns build android/ios
3.  npm i -D nativescript-dev-appium 
4. Update config/appim.capabilites.json and put your phone name ...
```
 "sim.iPhone7.iOS110": {
        "platformName": "iOS",
        "platformVersion": "11.0",
        "deviceName": "iPhone 7 110",
        "noReset": true,
        "fullReset": false,
        "app": ""
    }
```
5.  npm run e2e -- --runType sim.iPhone7.iOS110). 

Also when you install the plugin, please take a look at the project structure.

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov ,

When I follow the exact steps outlined by you, I get the error cannot find type definition file for chai (And mocha). 

Project structure is something like this.
hello-world
    -app
    -e2e
    -hooks
    -node_modules
    -package-lock.json
    -package.json
     -platforms
      -tsconfig.json

nativescript-dev-appium is found under node_modules

**Comment by SvetoslavTsenov** [comment]
Sorry, it is my mistake I forgot to mention you need to use next version nativescript-dev-appium. If you still get this error maybe you will need to add them explicitly as follows
npm i -D @types/chai ....

**Comment by gkvappium** [comment]
Ok, I managed to resolve the issue and got the test cases to execute. 

I installed all the mocha and chai dependencies manually and then I executed the command for the e2e folder under the main directory and not under nativescript-dev-appium which is under node_modules.

**Comment by SvetoslavTsenov** [comment]
This is how a single build looks in our CI for this application
https://github.com/NativeScript/nativescript-angular/tree/master/e2e/renderer
```
( 
  cd e2e/renderer
  npm i 
)


tns build ios --path e2e/renderer 

cd e2e/renderer
npm run e2e -- --runType sim.iPhone7.iOS110
```

**Comment by gkvappium** [comment]
Ok, thanks @SvetoslavTsenov . I'll also look forward to the new version which is lined up for release.

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov ,

Have you or anybody tried triggering the tests on an actual Iphone?, Looks like it works fine on android phone and android/ios emulators.

I have signed the webdriveragent with a valid dev cert (wda xcode project got built successfully). I am passing the xcconfig path and the automationName as XCUITest in the desired capabilities. But I always get an error saying that the requested environment is not available

**Comment by gkvappium** [comment]
I managed to resolve the issue @SvetoslavTsenov . Nothing to do with the helper plugin. There were problems in signing the webdriver agent after I re-did the setup. I managed to resolve the issue. I can confirm that it works on IOS physical hardware as well.

Thanks
