### ISSUE TITLE
How to use the same instance of the driver in different files

### ISSUE THREAD

**Issue by gkvappium** [NativeScript/nativescript-dev-appium#78]
Hi ,

When we use this
let driver:AppiumDriver;
driver = await createDriver();

Each time we open the driver.

I have created multiple page object files (Page object modelling) and different test case files. I need to use the instance of the driver in each of these files without opening multiple driver sessions. At the moment this in an async call (using await). How can I create a constructor since constructor returns an instance of the class and an async call will return a promise. 

Also if I want to have the elements in a separate file, it seems to be a problem because of asynchronous await.

@SvetoslavTsenov @vchimev can you please have a look?

**Comment by gkvappium** [comment]
@SvetoslavTsenov , can you please have a look and get back?

**Comment by gkvappium** [comment]
@SvetoslavTsenov ,

This is the only missing thing in the test framework. If you could have a look and provide your inputs, it would help.

**Comment by gkvappium** [comment]
@SvetoslavTsenov , Can you have a look and respond . Also could you please let me know when version 3.2.0 will be released

**Comment by gkvappium** [comment]
@radeva , sorry to ask this. Is there active development going on with respect to the plugin?

I've started to use this plugin and finding some issues with respect to the wrapper being async in nature. Is there somebody who can answer my queries? It's been unanswered from quite sometime

**Comment by SvetoslavTsenov** [comment]
Hey @gkvappium, I am sorry for delayed answer, but somehow I have dismisses notifications from the repo. 
I will try to answer to all your questions sequentially:

1. You can instantiate an instance of driver in a general hook of your tests. The logic behind appium driver is once it is created it will be used only this instance unless you call driver.quit(). With that said it has a similar behavior as a singleton object and this instance will be reused in all tests. Once you initiated it you can use it and passed it to the constructor off your object. Maybe you can try to create in each object an async method that returns the element you are searching when it is called. You can share with us your test project(or similar project) in case you still need some help or I have misunderstand you. 

2. " Is there active development going on with respect to the plugin?" - I will try to publish a newer version of the plugin as soon as possible with a lot of improvements including testing of animations.

**Comment by gkvappium** [comment]
@Svetoslav,

Thanks a lot for reverting back. I don't have any problem when I have the driver=await createDriver() in the before hook as part of mocha tests. I have divided the app into different screens. I need to use the instance of the driver in these files which are not part of the mocha tests. These are files created to isolate the UI from the actual test case or functionality. 

How can I share the project with you?

Will look forward for 3.2.0 as well. 

Thanks

**Comment by gkvappium** [comment]
@SvetoslavTsenov

**Comment by gkvappium** [comment]
@radeva , Not sure if @SvetoslavTsenov  is getting the alerts as mentioned in his previous reply. Can somebody look into this? I can upload the sample project as requested by Sveteslov.

**Comment by SvetoslavTsenov** [comment]
Hey @gkvappium  if you could share your project, it would be great for me. Please, have in mind that this could probably took a time because at the moment we are quite busy. I will try to provide you with a solution as soon as possible.

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov , It'd be great if you let me know as to where I can upload my sample project?

**Comment by SvetoslavTsenov** [comment]
Hi @gkvappium, if the project is not open ,you can send it to my email using google drive or something similar.

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov ,

I could send it to your mail. Could you please  share your email I'd? I can also briefly explain the problem in the mail.

**Comment by SvetoslavTsenov** [comment]
Hey @gkvappium I think I have made a mistake and it is not the best idea to use my email, but you can find me оn nativescriptcommunity.slack.com - SvetoslavTsenov

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov , I don't think I would be allowed to access this. I should be having an @telerik.com account to create an account. Is there any other way I can share this?

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov , It'll really help if we could find a way for me to share the sample project?

**Comment by gkvappium** [comment]
Hi @SvetoslavTsenov  @vchimev ,

I think uploading the project doesn't seems to be a viable option. But the thing is, there is no problem in using the driver instance in the test case file. 

I want to have a BasePage or an Abstract page where I have a driver constructor. I want to this instance (this.driver), in screen action pages or screen specific methods which are not part of the test case file. I don't want to keep using driver = await createDriver(); in each and every method in the screen action pages

This seems to be a problem because of the async nature. Having an async constructor in the BasePage or the AbstractPage seems to be a problem since theoretically it is not allowed. There are some workarounds that I tried. But none seems to work. Can you please have a look?

**Comment by gkvappium** [comment]
Closing this. Thanks @SvetoslavTsenov , solution provided by you on slack works fine.
