### ISSUE TITLE
All specs are falling in timeout

### ISSUE THREAD

**Issue by jeremypele** [NativeScript/nativescript-dev-appium#84]
Hey,

I've just set up the default spec provided created on the plugin installation.
It worked the very time but after that, it always fails due to timeout (currently 140000ms), the app is correctly launched and shown but the plugin isn't doing anything.
I'm using the latest version of the plugin on mac (w. nativescript 3.3.1)

Any idea what could cause that?

```
"sim.iPhone7": {
    "platformName": "iOS",
    "platformVersion": "11.2",
    "deviceName": "iPhone 7",
    "noReset": true,
    "fullReset": false,
    "app": ""
  },
```
Single test:
```
it('should display the logout screen', async () => {
  // Image verification
  const screen = await driver.compareScreen('homepage-logged-out')
  assert.isTrue(screen)
})
```
Output :
```

  0 passing (2m)
  2 failing

  1)  "before all" hook: start server:
     Error: Timeout of 140000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  2)  "after all" hook: stop server:
     TypeError: Cannot read property 'quit' of undefined
      at Object.<anonymous> (e2e/setup.js:18:17)
      at Generator.next (<anonymous>)
      at e2e/setup.js:7:71
      at Promise (<anonymous>)
      at __awaiter (e2e/setup.js:3:12)
      at Context.after (e2e/setup.js:17:28)

```

**Comment by Roar1827** [comment]
Hey @jeremypele - did you resolve this? We have the same error when trying to run on CircleCI.

**Comment by jeremypele** [comment]
@Roar1827 Yeah a bunch of reasons can cause that: 
- timeout isn't big enough in `mocha.opts`=> application don't get time to launch
- `before` hook that never resolves etc..
