### ISSUE TITLE
Add some more info on the different fields of capabilities

### ISSUE THREAD

**Issue by radeva** [NativeScript/nativescript-dev-appium#85]
Recently I had to configure the appium plugin with real device and it wasn't exactly clear how to do it by using the capabilities. More specifically what to enter as a deviceName and how to find the platformVersion. I think it would be nice to have more detailed documentation on each field for a capability description with more details how to get the values. For examples I used `adb devices` to find out what devices I had attached and I had to use the device name instead of the device identifier in the capabilities description.

**Comment by gkvappium** [comment]
@radeva , https://appium.io/docs/en/writing-running-appium/caps/ . Do have a look at this. Should help

**Comment by radeva** [comment]
Thanks @gkvappium ! This is really helpful. We will add a link in the README.
